const prefix = 'APP';

export const AppActions = {
  LOADING_START: `${prefix}_LOADING_START`,
  LOADING_STOP: `${prefix}_LOADING_STOP`,
  DATA_FETCH: `${prefix}_FETCH_DATA`,
  DATA_FETCH_SUCCESS: `${prefix}_DATA_FETCH_SUCCESS`,
  DATA_FETCH_ERROR: `${prefix}_DATA_FETCH_ERROR`,
  CHANGE_SEARCH_QUERY: `${prefix}_CHANGE_SEARCH_QUERY`,
  GET_NATIONALITIES_FROM_DATA: `${prefix}_GET_NATIONALITIES_FROM_DATA`,
  CHANGE_SELECTED_NATIONALITY: `${prefix}_CHANGE_SELECTED_NATIONALITY`,
  GET_GENDERS_FROM_DATA: `${prefix}_GET_GENDERS_FROM_DATA`,
  CHANGE_SELECTED_GENDER: `${prefix}_CHANGE_SELECTED_GENDER`,
};
